kind: pipeline
name: default

steps:
- name: start-notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: cicd
    template: >
        Build {{build.number}} of {{build.branch}} started. {{build.link}}
- name: build
  image: node:9.8.0
  commands:
  - sh ./.drone/build.sh
#- name: dockerhubpush 
#  image: plugins/docker
#  settings:
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#    repo: tintinthong/node-microservice
#- name: gcrpush 
#  image: plugins/gcr
#  settings:
#    registry: asia.gcr.io
#    repo: drone-251904/node-microservice
#    tags: latest
#    json_key: 
#      from_secret: google_credentials_base64 
- name: deploy
  image: docker
  commands:
  - sh ./.drone/deploy.sh
  volumes:
  - name: docker
    path: /var/run/docker.sock
- name: end-notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: cicd
    template: >
      {{#success build.status}}
        Build {{build.number}} of {{build.branch}} successful. {{build.link}}
      {{else}}
        Build {{build.number}} of {{build.branch}} failed. Please fix!. {{build.link}}
      {{/success}}
volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
type: ssh
name: sshpipeline 

server:
  host: root@165.22.104.56 
  ssh_key: 
    from_secret: ssh_key

steps:
- name: hello
  commands:
    - echo helloworld
