kind: pipeline
type: ssh
name: default

server:
  host: 165.22.104.56 
  user: root
  ssh_key:
    from_secret: ssh_key 

steps:
- name: touch
  commands:
  - mkdir hello 
- name: dockertest
  commands:
  - docker pull python 
  - docker run python
- name: gitclone
  commands: 
  - git clone  https://github.com/tintinthong/efficient-programmer.git
- name: dockertestimage
  image: docker
  commands:
  - docker pull busybox 
  volumes:
  - name: docker
    path: /var/run/docker.sock
