kind: pipeline
type: ssh
name: default

server:
  host: 165.22.104.56 
  user: root
  ssh_key:
    from_secret: ssh_key 

steps:
- name: touch
  commands:
  - touch ~/hello.txt 
  - echo "hello world" >> ~/hello.txt
- name: dockerpull 
  commands:
  - docker pull python 
