kind: pipeline
type: ssh
name: default

server:
  host: 165.22.104.56 
  user: root
  ssh_key:
    from_secret: ssh_key 

steps:
- name: mkdir 
  commands:
  - mkdir hi
- name: buildgo 
  commands:
  - go build
  - go test
  environment:
    GOOS: linux
    GOARCH: amd64
- name: build
  image: node:9.8.0
  commands:
  - sh ./.drone/build.sh
